### ISSUE TITLE
get /gates error

### ISSUE THREAD

**Issue by jharisonn** [2019-pemrogramanberbasiskerangkakerja-h/secure-gate-system-kelompoktanpafuad#1]

**Comment by cphikmawan** [comment]
![image](https://user-images.githubusercontent.com/22592235/57938693-df94cb00-78f2-11e9-88ab-dfa1a5ad0354.png)

Saya coba bisa, mohon dicoba kembali, dokumentasi API sudah saya perbaiki :)
