### ISSUE TITLE
get rules dan rules id tidak bisa 

### ISSUE THREAD

**Issue by jharisonn** [2019-pemrogramanberbasiskerangkakerja-h/secure-gate-system-kelompoktanpafuad#2]

**Comment by cphikmawan** [comment]
1. Get Rules
2. Get Rules id
![image](https://user-images.githubusercontent.com/22592235/57938592-b4aa7700-78f2-11e9-8a3c-7b544fadc17f.png)

Saya coba bisa, mohon maaf dokumentasi API kurang sip, sekarang sudah saya benahi, silahkan di coba
