### ISSUE TITLE
issue delete

### ISSUE THREAD

**Issue by geraldtamb** [2019-pemrogramanberbasiskerangkakerja-h/secure-gate-system-kelompoktanpafuad#3]
tidak bisa delete users dan gates

**Comment by cphikmawan** [comment]
![image](https://user-images.githubusercontent.com/22592235/58071368-a300f200-7bc6-11e9-8433-d1bc0b105b06.png)

sudah bisa, mohon maaf tadi koneksi ke dbnya error
